export AWS_ACCOUNT_ID="263704881331"
export APP_NAME="vhtds"
export AWS_DEFAULT_REGION="us-east-1"
export ENV_NAME="dev"
export AWS_PRIMARY_REGION="us-east-1"
export AWS_SECONDARY_REGION="us-east-2"
export TF_S3_BACKEND_NAME="vhtds-dev-tf-back-end"
